# Generated by Django 5.1.6 on 2025-11-03 09:50

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_create_roundtrip_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundtrip',
            name='time',
        ),
        migrations.AddField(
            model_name='roundtrip',
            name='time',
            field=models.TimeField(null=True, blank=True),
        ),
    ]
