# Generated by Django 5.1.6 on 2025-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20251103_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundtrip',
            old_name='drivercharge',
            new_name='driverCharge',
        ),
        migrations.AlterField(
            model_name='roundtrip',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
